### ISSUE TITLE
[Frontend] Find Match button bug

### ISSUE THREAD

**Issue by lambraydon** [CS3219-AY2425S1/cs3219-ay2425s1-project-g35#33]
- When a user presses  the Find Match button twice, the second Find Match will trigger an Internal Server Error and cause the countdown timer to refresh
- Frontend never calls the /cancel endpoint (which is triggered when the countdown timer hits 0) and user request is forever stuck in the redis queue
- Subsequent match requests will not work since user has an existing match request in the redis queue
<img width="1470" alt="Screenshot 2024-10-25 at 2 26 00 PM" src="https://github.com/user-attachments/assets/20147883-13a4-4579-9073-463fc1160474">

**Comment by yihfei** [comment]
Disabled button when waiting for match
